ALTER TABLE `documents` ADD `organization_id` text;--> statement-breakpoint
CREATE INDEX `documents_organization_id_idx` ON `documents` (`organization_id`);--> statement-breakpoint
ALTER TABLE `dowry` ADD `organization_id` text;--> statement-breakpoint
CREATE INDEX `dowry_organization_id_idx` ON `dowry` (`organization_id`);--> statement-breakpoint
ALTER TABLE `dresscodes` ADD `organization_id` text;--> statement-breakpoint
CREATE INDEX `dresscodes_organization_id_idx` ON `dresscodes` (`organization_id`);--> statement-breakpoint
ALTER TABLE `expense_categories` ADD `organization_id` text;--> statement-breakpoint
CREATE INDEX `expense_categories_organization_id_idx` ON `expense_categories` (`organization_id`);--> statement-breakpoint
ALTER TABLE `expense_items` ADD `organization_id` text;--> statement-breakpoint
CREATE INDEX `expense_items_organization_id_idx` ON `expense_items` (`organization_id`);--> statement-breakpoint
ALTER TABLE `savings_items` ADD `organization_id` text;--> statement-breakpoint
CREATE INDEX `savings_items_organization_id_idx` ON `savings_items` (`organization_id`);--> statement-breakpoint
ALTER TABLE `schedules` ADD `organization_id` text;--> statement-breakpoint
CREATE INDEX `schedules_organization_id_idx` ON `schedules` (`organization_id`);--> statement-breakpoint
ALTER TABLE `souvenirs` ADD `organization_id` text;--> statement-breakpoint
CREATE INDEX `souvenirs_organization_id_idx` ON `souvenirs` (`organization_id`);--> statement-breakpoint
ALTER TABLE `tasks` ADD `organization_id` text;--> statement-breakpoint
CREATE INDEX `tasks_organization_id_idx` ON `tasks` (`organization_id`);--> statement-breakpoint
ALTER TABLE `vendors` ADD `organization_id` text;--> statement-breakpoint
CREATE INDEX `vendors_organization_id_idx` ON `vendors` (`organization_id`);